### ISSUE TITLE
Problem url pada setiap tombol action

### ISSUE THREAD

**Issue by andrhmt** [masbudikusuma/neo-integrator#1]
Halo kak. Terima kasih untuk effortnya membuat neo-integrator. 
Hari ini sempat coba install, berikut kendala yang saya temukan :
Ketika di deploy menggunakan domain tombol action misal untuk Tarik data getMahasiswa ketika diklik url yang dipanggil tidak sempurna yaitu "https://exec.php/?act=getMahasiswa" nama domainnya tidak ada.

**Comment by masbudikusuma** [comment]
Yang digunakan versi berapa? Coba lihat di dashboard kanan bawah. 
Sudah saya update di versi release tanggal 15 Mei kemaren. 

Kalau intalasi pake git / git desktop tinggal di pull saja. Nanti otomatis ke update

**Comment by andrhmt** [comment]
> Yang digunakan versi berapa? Coba lihat di dashboard kanan bawah. Sudah saya update di versi release tanggal 15 Mei kemaren.
> 
> Kalau intalasi pake git / git desktop tinggal di pull saja. Nanti otomatis ke update

Halo. Ini sudah update ke versi per tanggal 16 Mei 2022 (tercantum di dashboard), tapi masih sama hasilnya.
Sudah "git pull origin master".

**Comment by masbudikusuma** [comment]
Bisa ditampilkan di Capture config.php nya?

**Comment by andrhmt** [comment]
`
<?php

include_once 'component/version.php';

$rootPath = $_SERVER['DOCUMENT_ROOT'];
$thisPath = dirname($_SERVER['PHP_SELF']);
$weburl = str_replace($rootPath, '', $thisPath);
  
// Konfigurasi Database Neo Integrator 
$db_server   = "xxx";
$db_username = "xxx";
$db_password = "xxx";
$db_database = "xxx";
$db = mysqli_connect($db_server,$db_username,$db_password,$db_database);

include_once 'component/ws_pddikti.php';

// AKUN PDDIKTI / NEO-FEEDER
$urlfeeder  = "xxx";   // contoh http://192.168.1.1:8100
$userfeeder = "xxx";   // User PDDIKTI
$passfeeder = "xxx";   // Pass PDDIKTI
$ws = new Ws_pddikti($urlfeeder."/ws/live2.php",$userfeeder,$passfeeder);

date_default_timezone_set("Asia/Bangkok");
$date = date('Y-m-d h:i:s', time());
$id_insert = time();

include_once 'component/ws_pddikti.php';
include_once 'component/function.php';
ini_set('max_execution_time', '100000');

?>
`

**Comment by andrhmt** [comment]
```
<?php

include_once 'component/version.php';

$rootPath = $_SERVER['DOCUMENT_ROOT'];
$thisPath = dirname($_SERVER['PHP_SELF']);
$weburl = str_replace($rootPath, '', $thisPath);
  
// Konfigurasi Database Neo Integrator 
$db_server   = "xxx";
$db_username = "xxx";
$db_password = "xxx";
$db_database = "xxx";
$db = mysqli_connect($db_server,$db_username,$db_password,$db_database);

include_once 'component/ws_pddikti.php';

// AKUN PDDIKTI / NEO-FEEDER
$urlfeeder  = "xxx";   // contoh http://192.168.1.1:8100
$userfeeder = "xxx";   // User PDDIKTI
$passfeeder = "xxx";   // Pass PDDIKTI
$ws = new Ws_pddikti($urlfeeder."/ws/live2.php",$userfeeder,$passfeeder);

date_default_timezone_set("Asia/Bangkok");
$date = date('Y-m-d h:i:s', time());
$id_insert = time();

include_once 'component/ws_pddikti.php';
include_once 'component/function.php';
ini_set('max_execution_time', '100000');

?>

```

**Comment by masbudikusuma** [comment]
Seharusnya Link Urlnya seperti ini belakangnya /exec.php?act=xxxxx

kalau ada anydesk bisa saya bantu remote,

![image](https://user-images.githubusercontent.com/58821556/168949681-7d8e07bf-bc3a-4092-931d-99a4fb4be7d8.png)

**Comment by andrhmt** [comment]
Halo. Terima kasih responnya. 
Sekarang sudah normal setelah saya baca postingan di group telegram. 
Saya set manual default urlnya menjadi seperti ini : 

```
//$rootPath = $_SERVER['DOCUMENT_ROOT'];
//$thisPath = dirname($_SERVER['PHP_SELF']);
//$weburl = str_replace($rootPath, '', $thisPath);
$weburl = "https://xxx.yyy.zzz/";
```
