### ISSUE TITLE
Matakuliah berhasil insert namun sks kurikulum yang tampil di neo feeder NaN

### ISSUE THREAD

**Issue by andrhmt** [masbudikusuma/neo-integrator#2]
Matakuliah berhasil insert namun sks kurikulum yang tampil di neo feeder NaN.

**Comment by masbudikusuma** [comment]
Ini di import matakuliah, atau matakuliah kurikulum kah? 

Bisa di capturekan hasilnya??

**Comment by mustz3n** [comment]
> Ini di import matakuliah, atau matakuliah kurikulum kah?
> 
> Bisa di capturekan hasilnya??

Import mata kuliah
![image](https://user-images.githubusercontent.com/105691735/168721309-f3a128b4-6eee-40ee-8799-5ec2dbdd3bc1.png)

**Comment by masbudikusuma** [comment]
Issue sudah diperbaiki di update version **17-05-2022**
