### ISSUE TITLE
Insert data kelas kuliah ke neofeeder tidak berfungsi

### ISSUE THREAD

**Issue by andrhmt** [masbudikusuma/neo-integrator#3]
Neofeeder yang digunakan versi 1.0.5b linux/docker.
Ketika menjalankan url https://domain.ac.id/exec.php/?act=insertKelasKuliah&tipe=minim
Hanya menampilkan pesan "JANGAN TUTUP BROWSER INI HINGGA PROSES SELESAI"
Tapi tidak ada data yang berhasil diinsert ke kelas kuliah neofeeder.
Di console browser menampilkan error "GET https://domain.ac.id/exec.php/?act=insertKelasKuliah&tipe=minim 500"

**Comment by masbudikusuma** [comment]
kalau ada telegram bisa Join ke Group ini kak : https://t.me/neointegrator

itu seharusnya linkya exec.php?act=xxxx bukan exec.php/?act
sepertinya ada yang salah di config.phpnya.

**Comment by andrhmt** [comment]
> kalau ada telegram bisa Join ke Group ini kak : https://t.me/neointegrator
> 
> itu seharusnya linkya exec.php?act=xxxx bukan exec.php/?act sepertinya ada yang salah di config.phpnya.

Baik mungkin saya typo. Setelah saya cek ulang urlnya : https://xxx.yyy.zzz/exec.php?act=insertKelasKuliah&tipe=minim

Tapi tetap sama Hanya menampilkan pesan "JANGAN TUTUP BROWSER INI HINGGA PROSES SELESAI"
Tapi tidak ada data yang berhasil diinsert ke kelas kuliah neofeeder.
Dan error di console sekarang menjadi "Failed to load resource: the server responded with a status of 500 ()"
